CREATE DATABASE TVC
USE TVC

CREATE TABLE BOLETO 
(UNIDAD NUMERIC (4),
NOMBRE_CHOFER VARCHAR (50),
VENTA VARCHAR (25),
ASIENTO CHAR (10),
DESTINO VARCHAR (18),
PRECIO VARCHAR (10),
HORARIO VARCHAR (8),
PRIMARY KEY (UNIDAD))

SELECT * FROM BOLETO

CREATE TABLE PASAJERO
(NOMBRE_PASAJERO VARCHAR (70),
SEXO VARCHAR (8),
TELEFONO NUMERIC (12),
PRIMARY KEY (NOMBRE_PASAJERO))

SELECT * FROM PASAJERO
